### PR TITLE
feat(browser): events.on

### PR DESCRIPTION
**Pull request by Mesteery**
*Not tested.*

### CODE REVIEW

**Comment by guybedford** [comment]
As much as possible we try to support older browsers when it comes to these features, because on JSPM you can even use the SystemJS CDN variant to support browsers without modules even. I only recently even started just using `const` here.

Would it be too much to ask to try implement it without using async functions and possibly even a `Symbol.asyncIterator` feature detection?

**Comment by guybedford** [comment]
Actually, async functions are relatively well established.

Note that previously these libraries have even supported IE11, but I guess the time has come to draw a line there finally.

So in that case async functions are fine... Aiming for the ES6 baseline seems sensible to me, so Firefox ~ 58 / Chrome ~60 / Safari 10.1 as the feature target.

**Comment by Mesteery** [comment]
Yes I understand perfectly. But there are features that are only available on very recent browsers and in this case I use recent things.

**Comment by guybedford** [comment]
Right, it's just that because we don't transpile these files we need to write the correct level of JS support directly for the browsers we are targetting.

**Pull request merged**
